name: habitstreaks
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  equatable: ^2.0.7
  path: ^1.9.0
  drift: ^2.24.0
  sqlite3_flutter_libs: ^0.5.29
  path_provider: ^2.1.5
  intl: ^0.20.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.25.8
  drift_dev: ^2.24.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  fonts:
    - family: icon_font_generator Icons
      fonts:
        - asset: assets/icons/CustomIcons.otf
  assets:
    - assets/
